Repository awslabs/fhir-works-on-aws-interface, pull requests merged in 2021-02, with the labels that each got.

#49 chore: add pr size labeler
  .github/workflows/labeler.yml
Labels: size/s

#48 feat: Add validator interface
  src/fhirConfig.ts
  src/index.ts
  src/validator.ts
Labels: size/s

#51 chore(release): 8.0.0
  CHANGELOG.md
  package.json
Labels: size/s

#53 chore: update ignore files
  .gitignore
  .npmignore
Labels: size/xs

#56 chore: update incorrect link
  src/fhirConfig.ts
Labels: documentation, size/xs
